# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &common
  slack:
    error_webhook_url: <%= ENV['SLACK_ERROR_WEBHOOK_URL'] %>
    error_channel: '<%= ENV['SLACK_ERROR_CHANNEL'] %>'
  oauth:
    pixiv:
      site: <%= ENV['OAUTH_PIXIV_SITE'] %>
      authorize_url: <%= ENV['OAUTH_PIXIV_AUTHORIZE_URL'] %>
      token_url: <%= ENV['OAUTH_PIXIV_TOKEN_URL'] %>
      key: <%= ENV['OAUTH_PIXIV_KEY'] %>
      secret: <%= ENV['OAUTH_PIXIV_SECRET'] %>
  pixiv_sdk:
    sdk_origin: <%= ENV['PIXIV_SDK_SDK_ORIGIN'] %>
    sdk_base: <%= ENV['PIXIV_SDK_SDK_BASE'] %>
  firebase_cloud_messaging_api_key: <%= ENV['FIREBASE_CLOUD_MESSAGING_API_KEY'] %>

development:
  <<: *common
  secret_key_base: d4398e4af52f1fc5be5c3c8764e9ecce7beac5462826cb8b649373b2aad5a0f133598ed817c4e9931e943041460d6b6eda40a854e825e1bbd510c4594b1538f2

test:
  <<: *common
  secret_key_base: 5be187ddbd651211a906f9aa399f4a148edf6e06b971c7c0b5429b9483df6e21d262cc846447d0f89b89c32d56a99e151039df5dd874ede7f712afbe041a9269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  oauth:
    pixiv:
      key: <%= ENV['OAUTH_PIXIV_KEY'] %>
      secret: <%= ENV['OAUTH_PIXIV_SECRET'] %>
  pixiv_sdk:
    sdk_origin: <%= ENV['OAUTH_PIXIV_SDK_ORIGIN'] %>
    sdk_base: <%= ENV['OAUTH_PIXIV_SDK_BASE'] %>
